### PR TITLE
feat: Add 19.x to the list of supported branches

### PR DESCRIPTION
**Pull request by mhdawson**
Need to add list of dependencies for 19.x

### CODE REVIEW

**Comment by mhdawson** [comment]
@facutuesca is there anything more that I need to do beyond this for this when we have a new major?

**Review by richardlau — APPROVED** [review]

**Comment by facutuesca** [comment]
> @facutuesca is there anything more that I need to do beyond this for this when we have a new major?

No, it is basically replicating the list of dependencies from `main` for the new major. This is assuming that `main` already has all the current dependencies and the corresponding logic to gather/parse their version number.

**Comment by richardlau** [comment]
Isn't this a duplicate of https://github.com/nodejs/nodejs-dependency-vuln-assessments/pull/71?

**Comment by facutuesca** [comment]
@richardlau Yeah I wrote my previous comment thinking I was on that PR instead. @mhdawson I opened #71 to fix the issue

**Review by RafaelGSS — APPROVED** [review]

**Comment by mhdawson** [comment]
Should have checked for PRs before submitting, closing.

**Pull request closed without merging**
